environment: dev

dev: 
  fastapi:
    host: "0.0.0.0"
    port: 8000
    reload: true
  endpoints:
    - path: "/api"
      method: ["GET"]
      response: 
        type: raw
        value: "Hello, World!" 
    - path: "/health"
      method: ["GET"]
      response: 
        type: json
        value: 
          status: "ok"
          uptime: 12345      